# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(db_column='IdUser', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=500)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('user_type', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('transporter', 'Transporter'), ('admin', 'Administrator')], default='buyer', max_length=20)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(db_column='IdUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(db_column='Role', default='Administrator', max_length=100)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user', models.OneToOneField(db_column='IdUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('buyer_balance', models.DecimalField(db_column='BuyerBalance', decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('user', models.OneToOneField(db_column='IdUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='farmer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_earnings', models.DecimalField(db_column='TotalEarnings', decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'db_table': 'Farmer',
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('user', models.OneToOneField(db_column='IdUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transporter_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('area_service', models.CharField(blank=True, db_column='AreaService', max_length=255, null=True)),
                ('delivery_earnings', models.DecimalField(db_column='DeliveryEarnings', decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_type', models.CharField(blank=True, db_column='VehicleType', max_length=100, null=True)),
                ('vehicle_capacity', models.DecimalField(blank=True, db_column='VehicleCapacity', decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('license_number', models.CharField(blank=True, db_column='LicenseNumber', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'db_table': 'Transporter',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('delivery', 'Delivery Request'), ('order', 'Order Update'), ('system', 'System Alert')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='validated_by',
            field=models.ForeignKey(blank=True, db_column='ValidatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_users', to='users.administrator'),
        ),
    ]
