# Generated by Django 4.2.7 on 2026-04-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_administrator_id_alter_administrator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, db_column='ProfilePicture', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('delivery', 'Delivery Request'), ('order', 'Order Update'), ('registration', 'User Registration'), ('system', 'System Alert')], default='system', max_length=20),
        ),
    ]
