# Generated by Django 4.2.7 on 2026-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.CharField(blank=True, db_column='Wilaya', max_length=100, null=True),
        ),
    ]
