# Generated by Django 4.2.7 on 2026-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, db_column='BirthDate', null=True),
        ),
    ]
