# Generated by Django 4.2.7 on 2026-04-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(db_column='LicenseNumber', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('REFRIGERATED', 'Refrigerated'), ('STANDARD', 'Standard'), ('SEMI-TRAILER', 'Semi-Trailer')], db_column='VehicleType', default='STANDARD', max_length=50)),
                ('capacity', models.DecimalField(db_column='Capacity', decimal_places=2, default=0.0, max_digits=10)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=100, null=True)),
                ('area_service', models.CharField(blank=True, db_column='AreaService', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transporter', models.ForeignKey(db_column='IdTransporter', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.transporter')),
            ],
            options={
                'db_table': 'TransporterVehicle',
            },
        ),
    ]
