# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMission',
            fields=[
                ('mission_number', models.AutoField(db_column='MissionNumber', primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(auto_now_add=True, db_column='DeliveryDate')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned')], db_column='DeliveryStatus', default='pending', max_length=20)),
                ('delivery_location', models.CharField(db_column='DeliveryLocation', max_length=255)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lng', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('delivery_latitude', models.FloatField(blank=True, null=True)),
                ('delivery_longitude', models.FloatField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DeliveryMission',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
