# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymission',
            name='id_order',
            field=models.ForeignKey(db_column='IdOrder', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_missions', to='orders.order'),
        ),
    ]
