# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymission',
            name='id_transporter',
            field=models.ForeignKey(blank=True, db_column='IdTransporter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_missions', to='users.transporter'),
        ),
    ]
