# Generated by Django 4.2.7 on 2026-04-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymission',
            name='vehicle_license_snapshot',
            field=models.CharField(blank=True, db_column='VehicleLicenseSnapshot', max_length=50, null=True),
        ),
    ]
