# Generated by Django 4.2.7 on 2026-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_deliverymission_vehicle_license_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymission',
            name='delivery_status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('returned', 'Returned')], db_column='DeliveryStatus', default='open', max_length=20),
        ),
    ]
