# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(db_column='OrderNumber', primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True, db_column='OrderDate')),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_column='OrderStatus', default='pending', max_length=20)),
                ('total_amount', models.FloatField(blank=True, db_column='TotalAmount', null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial', 'Partial')], db_column='PaymentStatus', default='pending', max_length=20)),
                ('invoice_number', models.CharField(blank=True, db_column='InvoiceNumber', max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, db_column='InvoiceDate', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, db_column='DeliveryAddress', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '`Order`',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_order_item', models.AutoField(db_column='IdOrderItem', primary_key=True, serialize=False)),
                ('quantity_item', models.FloatField(db_column='QuantityItem')),
                ('quantity_unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('ton', 'Ton (t)'), ('litre', 'Litre (L)')], db_column='QuantityUnit', default='kg', max_length=20)),
                ('price_item', models.FloatField(db_column='PriceItem')),
                ('sub_total_item', models.FloatField(blank=True, db_column='SubTotalItem', null=True)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('id_order', models.ForeignKey(db_column='IdOrder', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
