# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_buyer',
            field=models.ForeignKey(db_column='IdBuyer', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_farmer',
            field=models.ForeignKey(db_column='IdFarmer', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.farmer'),
        ),
    ]
