# Generated by Django 4.2.7 on 2026-04-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_rating',
            field=models.IntegerField(blank=True, db_column='BuyerRating', null=True),
        ),
    ]
