# Generated by Django 4.2.7 on 2026-04-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_administrator_id_alter_administrator_user'),
        ('orders', '0003_order_buyer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_rating',
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id_appraisal', models.AutoField(db_column='IdAppraisal', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_column='Rating', default=5)),
                ('feedback', models.TextField(blank=True, db_column='Feedback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('id_buyer', models.ForeignKey(db_column='IdBuyer', on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='users.buyer')),
                ('id_farmer', models.ForeignKey(db_column='IdFarmer', on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='users.farmer')),
                ('id_order', models.OneToOneField(db_column='IdOrder', on_delete=django.db.models.deletion.CASCADE, related_name='appraisal', to='orders.order')),
            ],
            options={
                'verbose_name': 'Appraisal',
                'verbose_name_plural': 'Appraisals',
                'db_table': 'Appraisal',
            },
        ),
    ]
