# Generated by Django 4.2.7 on 2026-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_buyer_rating_appraisal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, db_column='TotalAmount', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_item',
            field=models.DecimalField(db_column='PriceItem', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_item',
            field=models.DecimalField(db_column='QuantityItem', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sub_total_item',
            field=models.DecimalField(blank=True, db_column='SubTotalItem', decimal_places=2, max_digits=12, null=True),
        ),
    ]
