# Generated by Django 4.2.7 on 2026-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_total_amount_alter_orderitem_price_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, db_column='TotalAmount', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_item',
            field=models.FloatField(db_column='PriceItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_item',
            field=models.FloatField(db_column='QuantityItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sub_total_item',
            field=models.FloatField(blank=True, db_column='SubTotalItem', null=True),
        ),
    ]
