# Generated by Django 4.2.7 on 2026-04-13 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('IdFarm', models.AutoField(primary_key=True, serialize=False, verbose_name='Farm ID')),
                ('FarmName', models.CharField(db_index=True, max_length=200, verbose_name='Farm Name')),
                ('LocationFarm', models.TextField(verbose_name='Location')),
                ('Size', models.FloatField(help_text='Size in hectares, minimum 0.01 ha', validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Size (hectares)')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the farm', verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude coordinate', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude coordinate', max_digits=10, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'db_table': 'farms',
                'ordering': ['-created_at'],
            },
        ),
    ]
