# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='users.farmer', verbose_name='Farmer'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['FarmName'], name='idx_farm_name'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['farmer', 'created_at'], name='idx_farmer_created'),
        ),
    ]
