# Generated by Django 4.2.7 on 2026-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='farm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='farm',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
