# Generated by Django 4.2.7 on 2026-04-28 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_address_farm_email_farm_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='Size',
            field=models.DecimalField(decimal_places=2, help_text='Size in hectares, minimum 0.01 ha', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Size (hectares)'),
        ),
    ]
