# Generated by Django 6.0.4 on 2026-05-02 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='Size',
            field=models.FloatField(help_text='Size in hectares, minimum 0.01 ha', validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Size (hectares)'),
        ),
    ]
