import React from 'react';
import { FaFileInvoice, FaCheckCircle, FaPrint, FaDownload, FaBuilding } from 'react-icons/fa';

const mockInvoices = [
  { id: 'REC-2026-89F2', date: 'March 28, 2026', total: 52000, status: 'Paid via COD', items: 2 },
  { id: 'REC-2026-71A4', date: 'March 15, 2026', total: 110500, status: 'Paid via COD', items: 5 },
  { id: 'REC-2026-66B1', date: 'February 28, 2026', total: 45000, status: 'Bank Transfer', items: 1 },
];

const Invoice = () => {
  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col md:flex-row justify-between items-start md:items-center">
        <div className="flex items-center">
           <div className="bg-[#e3f0dc] p-3 rounded-lg text-[#4b6d3a] mr-4 shadow-sm">
             <FaFileInvoice size={24} />
           </div>
           <div>
             <h1 className="text-2xl font-normal text-gray-800">Official Invoices & Receipts</h1>
             <p className="text-gray-500 text-sm mt-1">Access tax-compliant transaction records generated by the AgriGov platform.</p>
           </div>
        </div>
        <div className="mt-4 md:mt-0 bg-yellow-50 text-yellow-700 font-normal px-4 py-2 rounded border border-yellow-200 shadow-sm text-sm flex items-center">
           <FaCheckCircle className="mr-2" /> All accounts balanced for Q1
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {mockInvoices.map((invoice) => (
          <div key={invoice.id} className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 flex flex-col sm:flex-row justify-between items-start sm:items-center hover:shadow-md transition-shadow group">
             <div className="flex items-center w-full sm:w-1/2 mb-4 sm:mb-0">
               <div className="bg-gray-50 p-4 rounded-full text-gray-400 mr-5 hidden sm:block border border-gray-200">
                  <FaBuilding size={20} />
               </div>
               <div>
                  <h3 className="font-normal text-lg text-gray-800 group-hover:text-[#4b6d3a] transition-colors cursor-pointer">{invoice.id}</h3>
                  <div className="flex items-center text-sm text-gray-500 mt-1 space-x-3">
                     <span>{invoice.date}</span>
                     <span>•</span>
                     <span>{invoice.items} Purchased Items</span>
                  </div>
               </div>
             </div>
             
             <div className="flex flex-col sm:flex-row items-start sm:items-center w-full sm:w-1/2 justify-between">
                <div className="mb-4 sm:mb-0 sm:mr-8">
                   <p className="text-xs text-gray-400 font-normal uppercase tracking-wider mb-1">Total Settled</p>
                   <p className="font-normal text-xl text-gray-800">{invoice.total.toLocaleString()} DZD</p>
                   <p className="text-xs font-normal text-green-600 bg-green-50 px-2 py-0.5 rounded border border-green-200 inline-block mt-1">
                     {invoice.status}
                   </p>
                </div>
                
                <div className="flex space-x-2 w-full sm:w-auto">
                   <button className="flex-1 sm:flex-none border border-gray-300 text-gray-600 px-4 py-2.5 rounded-lg font-normal hover:bg-gray-50 transition-colors flex items-center justify-center">
                      <FaPrint className="mr-2" /> Print
                   </button>
                   <button className="flex-1 sm:flex-none bg-[#4b6d3a] text-white px-4 py-2.5 rounded-lg font-normal hover:bg-[#3d592f] transition-colors shadow-sm flex items-center justify-center">
                      <FaDownload className="mr-2" /> PDF Copy
                   </button>
                </div>
             </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Invoice;