# Generated by Django 6.0.4 on 2026-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reports/')),
                ('report_type', models.CharField(choices=[('PDF', 'PDF Document'), ('Excel', 'Excel Spreadsheet')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
