# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('category_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.FloatField(db_column='MaxPrice', verbose_name='Maximum Price')),
                ('min_price', models.FloatField(db_column='MinPrice', verbose_name='Minimum Price')),
                ('price_unit', models.CharField(db_column='PriceUnit', default='DZD/kg', max_length=20, verbose_name='Price Unit')),
                ('date_set', models.DateField(auto_now_add=True, db_column='DateSet', verbose_name='Date Set')),
                ('valid_until', models.DateField(blank=True, db_column='ValidUntil', null=True, verbose_name='Valid Until')),
            ],
            options={
                'verbose_name': 'Official Price',
                'verbose_name_plural': 'Official Prices',
                'db_table': 'PriceOff',
                'ordering': ['-date_set'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('product_quality', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], default='standard', max_length=20, verbose_name='Quality')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(db_column='Quantity', verbose_name='Quantity')),
                ('product_price', models.FloatField(db_column='ProductPrice', verbose_name='Unit Price')),
                ('item_date', models.DateField(auto_now_add=True, db_column='ItemDate', verbose_name='Item Date')),
                ('production_date', models.DateField(db_column='ProductionDate', verbose_name='Production Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Product Item',
                'verbose_name_plural': 'Product Items',
                'db_table': 'ProductItem',
                'ordering': ['-item_date'],
            },
        ),
    ]
