# Generated by Django 4.2.7 on 2026-04-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='id_farmer',
            field=models.ForeignKey(db_column='IdFarmer', on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='users.farmer', verbose_name='Farmer'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='id_order_item',
            field=models.ForeignKey(blank=True, db_column='IdOrderItem', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='id_product',
            field=models.ForeignKey(db_column='IdProduct', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_category',
            field=models.ForeignKey(db_column='IdCategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='priceoff',
            name='id_admin',
            field=models.ForeignKey(db_column='IdAdmin', on_delete=django.db.models.deletion.CASCADE, to='users.administrator', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='priceoff',
            name='id_product',
            field=models.ForeignKey(db_column='IdProduct', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='id_admin',
            field=models.ForeignKey(db_column='IdAdmin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='users.administrator', verbose_name='Admin'),
        ),
        migrations.AlterUniqueTogether(
            name='priceoff',
            unique_together={('id_product', 'date_set')},
        ),
    ]
