# Generated by Django 4.2.7 on 2026-04-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='id_farm',
            field=models.ForeignKey(blank=True, db_column='IdFarm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_items', to='farms.farm', verbose_name='Farm Source'),
        ),
    ]
