# Generated by Django 4.2.7 on 2026-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_id_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL'),
        ),
    ]
