# Generated by Django 4.2.7 on 2026-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_items/', verbose_name='Product Image'),
        ),
    ]
