# Generated by Django 4.2.7 on 2026-04-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productitem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_category',
            field=models.ForeignKey(db_column='IdCategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Category'),
        ),
    ]
