# Generated by Django 4.2.7 on 2026-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_id_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceoff',
            name='max_price',
            field=models.DecimalField(db_column='MaxPrice', decimal_places=2, max_digits=12, verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='priceoff',
            name='min_price',
            field=models.DecimalField(db_column='MinPrice', decimal_places=2, max_digits=12, verbose_name='Minimum Price'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_price',
            field=models.DecimalField(db_column='ProductPrice', decimal_places=2, max_digits=12, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=12, verbose_name='Quantity'),
        ),
    ]
