# Generated by Django 4.2.7 on 2026-04-30 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_priceoff_max_price_alter_priceoff_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceoff',
            name='max_price',
            field=models.FloatField(db_column='MaxPrice', verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='priceoff',
            name='min_price',
            field=models.FloatField(db_column='MinPrice', verbose_name='Minimum Price'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_price',
            field=models.FloatField(db_column='ProductPrice', verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.FloatField(db_column='Quantity', verbose_name='Quantity'),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_price', models.FloatField(verbose_name='Average Price')),
                ('history_date', models.DateField(default=django.utils.timezone.now, verbose_name='History Date')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Price History',
                'verbose_name_plural': 'Product Price Histories',
                'db_table': 'ProductPriceHistory',
                'ordering': ['-history_date'],
                'unique_together': {('id_product', 'history_date')},
            },
        ),
    ]
